---
- name: memory monitoring play
  hosts: all
  tasks:
    - name: copy memory monitoring shellscript
      copy:
        src: memmonitor.sh
        dest: /home/vagrant/
        mode: 0554
    - name: copy memory monitoring serviceunit file
      copy:
        src: memmonitor.service
        dest: /etc/systemd/system/
      become: yes
    - name: service daemon reload
      service:
        name: memmonitor
        state: reloaded
      become: yes
    - name: enable memorymonitoring service
      service:
        name: memmonitor
        enabled: yes
      become: yes
...
