---
- name: new service play
  hosts: all
  vars_files:
    - service_vars.yml
  tasks:
    - name: copy shell program
      copy:
        src: "{{shellprogram}}"
        dest: /home/vagrant
    - name: copy service unit
      copy:
        src: "{{servicefile}}"
        dest: /etc/systemd/system/
      become: yes
    - name: reload service
      service:
        name: "{{servicename}}"
        state: reloaded
      become: yes
    - name: enable service
      service:
        name: "{{servicename}}"
        enabled: yes
      become: yes
...
