- name: loop thru hashes
  hosts: all
  vars:
    users:
     - {user: "bob", uid: 1010, group: "devopsgroup", shell_type: "/bin/sh", create_home: "yes"}
     - {user: "greg", uid: 1011, group: "devopsgroup", shell_type: "/bin/bash", create_home: "no"}
     - {user: "mike", uid: 1011, group: "devopsgroup", shell_type: "/bin/sh", create_home: "yes"}
  tasks:
    - name: create linux users
      user:
        name: "{{item.user}}"
        uid: "{{item.uid}}"
        group: "{{item.group}}"
        shell: "{{item.shell_type}}"
        create_home: "{{item.create_home}}"
      become: yes
      loop: "{{users}}"
