---
- name: loop thru dictionaries
  hosts: all
  vars:
    sprint1:
      login_story: in_progress
      registration_design_spike: pending
      forgot_password_story: ready_for_qa
      bug_support: completed
  tasks:
    - name: show sprint tasks
      debug:
        msg: "task : {{item.key}} and status: {{item.value}}"
      loop: "{{sprint1 | dict2items}}"

...
