---
- name: create linux user play
  hosts: all
  tasks:
    - name: create linux user
      user:
        name: "{{linuxuser}}"
        uid: "{{uid}}"
        create_home: "{{create_home}}"
        shell: "{{shell_type}}"
        state: present
      become: yes
...
