---
- name: new file play
  hosts: all
  vars:
    owner: vagrant
    group: vagrant
    perm: 0655
  tasks:
    - name: new empty file
      file:
        name: "{{filename}}"
        owner: "{{owner}}"
        group: "{{group}}"
        mode: "{{perm}}"
        state: touch
...
