---
- name: addNumbers Play
  hosts: all
  tasks:
    - name: execute addNumbers shell program
      expect:
        command: ./addNumbers.sh
        responses:
          "Enter A :": 10
          "Enter B :": 20
      register: sum
    - name: print sum
      debug:
        msg: "sum {{sum}}"
...
