---
- name: download and setup tomcat play
  hosts: all
  tasks:
    - name: find tomcat directory
      find:
        paths: /home/vagrant
        patterns: "apache-tomcat-*"
        use_regex: yes
        recurse: no
        file_type: directory
      register: tomcatstatus
    - name: download tomcat server
      get_url:
        url: "{{tomcat_url}}"
        dest: /home/vagrant
        mode: '0655'
      when: "{{tomcatstatus.matched | float == 0}}"
...

