---
- name: install vscode on linux
  hosts: all
  tasks:
    - name: download vscode on Debain
      get_url:
        url: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64
        dest: /tmp/
      when: ansible_os_family == "Debian"
    - name: download vscode on Redhat
      get_url:
        url: https://code.visualstudio.com/sha/download?build=stable&os=linux-rpm-x64
        dest: /tmp
      when: ansible_os_family == "Redhat"
    - name: install vscode Debain
      apt:
        deb: /tmp/code_1.84.0-1698839401_amd64.deb
        state: present
      become: yes
      when: ansible_os_family == "Debian"
    - name: install vscode Redhat
      yum:
        name: /tmp/code-1.84.0-1698839485.el7.x86_64.rpm
        state: present
      become: yes
      when: ansible_os_family == "Redhat"

...
