---
- name: timestamps play
  hosts: all
  tasks:
    - name: change permissions
      file:
        path: /home/vagrant/file1.txt
        mode: 0664
        modification_time: preserve
        access_time: preserve
...
