---
- name: handlers play
  hosts: all
  tasks:
    - name: create servers file
      file:
        path: ~/servers.xml
        state: touch
        access_time: preserve
        modification_time: preserve
      notify:
        - loggingHandler
    - name: create users file
      file:
        path: ~/users.xml
        state: touch
  handlers:
    - name: loggingHandler
      debug:
        msg: servers.xml has been created
...

